import Document, { Html, Head, Main, NextScript } from "next/document";
import { CssBaseline } from "@geist-ui/core";
import { Global } from "@emotion/react";
import globalStyles from "../components/styled/global";

class MyDocument extends Document {
  static async getInitialProps(ctx: any) {
    const initialProps = await Document.getInitialProps(ctx);
    const styles = CssBaseline.flush();

    return {
      ...initialProps,
      styles: (
        <>
          {initialProps.styles}
          {styles}
          <Global styles={globalStyles} />
        </>
      ),
    };
  }

  render() {
    return (
      <Html>
        <Head>
          <meta
            name="description"
            content="Anilist Collection App | generated by create next app"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
